# Issue month: months corresponding to the forecasts used for monitoring
issue_months:
  - "05"
  - "06"
  - "07"
  - "08"
  - "09"
  - "10"
  - "11"
  - "12"
  - "01"
  - "02"

# First year of season to monitor operationally (e.g. 2024 for 2024/2025 season)
monitoring_year: 2026

# Last year of calibration period used for triggers selection (e.g. 2022 for 1981-2022)
calibration_year: 2026

# Month from which the monitoring starts (e.g. 5 if the first predictions are produced in May)
start_monitoring: 5

# Minimum length of indicator periods (ON, NDJ, JFMA...)
min_index_period: 2

# Maximum length of indicator periods (ON, NDJ, JFMA...)
max_index_period: 3

# First month of the wet season
start_season: 10

# Last month of the wet season
end_season: 3

# Start date of historical time series used in anomaly computation
hist_anomaly_start: "1991-01-01"

# End date of historical time series used in anomaly computation
hist_anomaly_stop: "2020-12-31"

# Save (and overwrite if exists) ds (obs or probs) for future trigger choice
save_zarr: true

# Thresholds defining different drought intensities used in probabilities computation
intensity_thresholds:
  Moderate: -0.85
  Normal: -0.44

# Vulnerability class of triggers for each district: general or non-regret (GT or NRT)
districts_vulnerability: 
  Beitbridge: "TBD"
  Beitbridge Urban: "TBD"
  Bikita: "TBD"
  Bindura: "TBD"
  Binga: "TBD"
  Bubi: "TBD"
  Buhera: "TBD"
  Bulawayo: "TBD"
  Bulilima: "TBD"
  Centenary: "TBD"
  Chegutu: "TBD"
  Chegutu Urban: "TBD"
  Chikomba: "TBD"
  Chimanimani: "TBD"
  Chinhoyi: "TBD"
  Chipinge: "TBD"
  Chipinge Urban: "TBD"
  Chiredzi: "TBD"
  Chirumhanzu: "TBD"
  Chivi: "TBD"
  Gokwe North: "TBD"
  Gokwe South: "TBD"
  Gokwe South Urban: "TBD"
  Goromonzi: "TBD"
  Guruve: "TBD"
  Gutu: "TBD"
  Gwanda: "TBD"
  Gweru: "TBD"
  Gweru Urban: "TBD"
  Harare: "TBD"
  Hurungwe: "TBD"
  Hwange: "TBD"
  Hwange Urban: "TBD"
  Hwedza: "TBD"
  Insiza: "TBD"
  Kadoma Urban: "TBD"
  Kariba: "TBD"
  Kariba Urban: "TBD"
  Karoi: "TBD"
  Kwekwe: "TBD"
  Lupane: "TBD"
  Makonde: "TBD"
  Makoni: "TBD"
  Mangwe: "TBD"
  Marondera: "TBD"
  Marondera Urban: "TBD"
  Masvingo: "TBD"
  Masvingo Urban: "TBD"
  Matobo: "TBD"
  Mazowe: "TBD"
  Mberengwa: "TBD"
  Mbire: "TBD"
  Mhondoro-Ngezi: "TBD"
  Mount Darwin: "TBD"
  Mudzi: "TBD"
  Murehwa: "TBD"
  Mutare: "TBD"
  Mutare Urban: "TBD"
  Mutasa: "TBD"
  Mutoko: "TBD"
  Mvurwi: "TBD"
  Mwenezi: "TBD"
  Nkayi: "TBD"
  Nyanga: "TBD"
  Plumtree: "TBD"
  Redcliff: "TBD"
  Rusape: "TBD"
  Rushinga: "TBD"
  Ruwa: "TBD"
  Sanyati: "TBD"
  Seke: "TBD"
  Shamva: "TBD"
  Shurugwi: "TBD"
  Shurugwi Town: "TBD"
  Tsholotsho: "TBD"
  Umguza: "TBD"
  Umzingwane: "TBD"
  Uzumba Maramba Pfungwe: "TBD" 
  Victoria Falls: "TBD"
  Zaka: "TBD"
  Zvimba: "TBD"
  Zvishavane: "TBD"
  Zvishavane Urban: "TBD"

# Tolerance for thresholds for each category, used to compute false alarm with tolerance
tolerance:
  Normal: 0
  Mild: 0
  Moderate: -0.44
  Severe: -0.68

# Skill requirements for General Triggers
general_t:
  HR: 0.55 # 0.5  # W/out exceptions: HR=0.55
  SR: 0.55
  FR: 0.45
  RP: 4.0

# Skill requirements for Non Regret Triggers
non_regret_t:
  HR: 0.7 # 0.5  # W/out exceptions: HR=0.70
  SR: 0.55
  FR: 0.45
  RP: 3.0

# Window definitions for SPI and DRYSPELL indicators
windows:
  spi:
    window1: ["ON", "ND", "OND", "NDJ"]
    window2: ["DJ", "JF", "FM", "DJF", "JFM", "FMA"]
  dryspell:
    window1: ["ON", "ND"]
    window2: ["DJ", "JF", "FM"]

